package com.seesea.seeseagateway.mapper;

import com.seesea.seeseagateway.entity.AccountInfo;
import java.util.List;

public interface AccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    int deleteByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    int insert(AccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    AccountInfo selectByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    List<AccountInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    int updateByPrimaryKey(AccountInfo record);
}