package com.seesea.seeseagateway.mapper;

import com.seesea.seeseagateway.entity.GatewayLog;
import com.seesea.seeseagateway.entity.GatewayLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GatewayLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbg.generated Wed Dec 02 20:31:38 CST 2020
     */
    long countByExample(GatewayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbg.generated Wed Dec 02 20:31:38 CST 2020
     */
    int deleteByExample(GatewayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbg.generated Wed Dec 02 20:31:38 CST 2020
     */
    int deleteByPrimaryKey(@Param("reqId") String reqId, @Param("sequenceId") String sequenceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbg.generated Wed Dec 02 20:31:38 CST 2020
     */
    int insert(GatewayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbg.generated Wed Dec 02 20:31:38 CST 2020
     */
    int insertSelective(GatewayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbg.generated Wed Dec 02 20:31:38 CST 2020
     */
    List<GatewayLog> selectByExample(GatewayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbg.generated Wed Dec 02 20:31:38 CST 2020
     */
    GatewayLog selectByPrimaryKey(@Param("reqId") String reqId, @Param("sequenceId") String sequenceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbg.generated Wed Dec 02 20:31:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") GatewayLog record, @Param("example") GatewayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbg.generated Wed Dec 02 20:31:38 CST 2020
     */
    int updateByExample(@Param("record") GatewayLog record, @Param("example") GatewayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbg.generated Wed Dec 02 20:31:38 CST 2020
     */
    int updateByPrimaryKeySelective(GatewayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbg.generated Wed Dec 02 20:31:38 CST 2020
     */
    int updateByPrimaryKey(GatewayLog record);
}