package com.seesea.seeseagateway.mapper;

import com.seesea.seeseagateway.entity.ServiceInfo;
import java.util.List;

public interface ServiceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    int deleteByPrimaryKey(String serviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    int insert(ServiceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    ServiceInfo selectByPrimaryKey(String serviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    List<ServiceInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    int updateByPrimaryKey(ServiceInfo record);
}