package com.seesea.seeseasms.entity;

import java.io.Serializable;

public class SmsChannel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.sms_channel_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsChannelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.sms_channel_name
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsChannelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.sms_channel_key
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsChannelKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.sms_channel_account
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsChannelAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.sms_channel_pwd
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsChannelPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.remainder
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private Long remainder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.status
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_channel.remark
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_channel
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.sms_channel_id
     *
     * @return the value of sms_channel.sms_channel_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsChannelId() {
        return smsChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.sms_channel_id
     *
     * @param smsChannelId the value for sms_channel.sms_channel_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsChannelId(String smsChannelId) {
        this.smsChannelId = smsChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.sms_channel_name
     *
     * @return the value of sms_channel.sms_channel_name
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsChannelName() {
        return smsChannelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.sms_channel_name
     *
     * @param smsChannelName the value for sms_channel.sms_channel_name
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsChannelName(String smsChannelName) {
        this.smsChannelName = smsChannelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.sms_channel_key
     *
     * @return the value of sms_channel.sms_channel_key
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsChannelKey() {
        return smsChannelKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.sms_channel_key
     *
     * @param smsChannelKey the value for sms_channel.sms_channel_key
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsChannelKey(String smsChannelKey) {
        this.smsChannelKey = smsChannelKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.sms_channel_account
     *
     * @return the value of sms_channel.sms_channel_account
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsChannelAccount() {
        return smsChannelAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.sms_channel_account
     *
     * @param smsChannelAccount the value for sms_channel.sms_channel_account
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsChannelAccount(String smsChannelAccount) {
        this.smsChannelAccount = smsChannelAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.sms_channel_pwd
     *
     * @return the value of sms_channel.sms_channel_pwd
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsChannelPwd() {
        return smsChannelPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.sms_channel_pwd
     *
     * @param smsChannelPwd the value for sms_channel.sms_channel_pwd
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsChannelPwd(String smsChannelPwd) {
        this.smsChannelPwd = smsChannelPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.remainder
     *
     * @return the value of sms_channel.remainder
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public Long getRemainder() {
        return remainder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.remainder
     *
     * @param remainder the value for sms_channel.remainder
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setRemainder(Long remainder) {
        this.remainder = remainder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.status
     *
     * @return the value of sms_channel.status
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.status
     *
     * @param status the value for sms_channel.status
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_channel.remark
     *
     * @return the value of sms_channel.remark
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_channel.remark
     *
     * @param remark the value for sms_channel.remark
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", smsChannelId=").append(smsChannelId);
        sb.append(", smsChannelName=").append(smsChannelName);
        sb.append(", smsChannelKey=").append(smsChannelKey);
        sb.append(", smsChannelAccount=").append(smsChannelAccount);
        sb.append(", smsChannelPwd=").append(smsChannelPwd);
        sb.append(", remainder=").append(remainder);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}