package com.seesea.seeseasms.entity;

import java.io.Serializable;
import java.util.Date;

public class SmsLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.sms_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.req_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String reqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.sms_channl_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsChannlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.sms_req_log
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsReqLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.sms_rsp_log
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsRspLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.req_time
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private Date reqTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.rsp_time
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private Date rspTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_log
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.sms_id
     *
     * @return the value of sms_log.sms_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsId() {
        return smsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.sms_id
     *
     * @param smsId the value for sms_log.sms_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsId(String smsId) {
        this.smsId = smsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.req_id
     *
     * @return the value of sms_log.req_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getReqId() {
        return reqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.req_id
     *
     * @param reqId the value for sms_log.req_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setReqId(String reqId) {
        this.reqId = reqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.sms_channl_id
     *
     * @return the value of sms_log.sms_channl_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsChannlId() {
        return smsChannlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.sms_channl_id
     *
     * @param smsChannlId the value for sms_log.sms_channl_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsChannlId(String smsChannlId) {
        this.smsChannlId = smsChannlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.sms_req_log
     *
     * @return the value of sms_log.sms_req_log
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsReqLog() {
        return smsReqLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.sms_req_log
     *
     * @param smsReqLog the value for sms_log.sms_req_log
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsReqLog(String smsReqLog) {
        this.smsReqLog = smsReqLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.sms_rsp_log
     *
     * @return the value of sms_log.sms_rsp_log
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsRspLog() {
        return smsRspLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.sms_rsp_log
     *
     * @param smsRspLog the value for sms_log.sms_rsp_log
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsRspLog(String smsRspLog) {
        this.smsRspLog = smsRspLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.req_time
     *
     * @return the value of sms_log.req_time
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public Date getReqTime() {
        return reqTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.req_time
     *
     * @param reqTime the value for sms_log.req_time
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setReqTime(Date reqTime) {
        this.reqTime = reqTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.rsp_time
     *
     * @return the value of sms_log.rsp_time
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public Date getRspTime() {
        return rspTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.rsp_time
     *
     * @param rspTime the value for sms_log.rsp_time
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setRspTime(Date rspTime) {
        this.rspTime = rspTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_log
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", smsId=").append(smsId);
        sb.append(", reqId=").append(reqId);
        sb.append(", smsChannlId=").append(smsChannlId);
        sb.append(", smsReqLog=").append(smsReqLog);
        sb.append(", smsRspLog=").append(smsRspLog);
        sb.append(", reqTime=").append(reqTime);
        sb.append(", rspTime=").append(rspTime);
        sb.append("]");
        return sb.toString();
    }
}