package com.seesea.seeseasms.entity;

import java.io.Serializable;
import java.util.Date;

public class SmsSendCheck implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.sms_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.req_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String reqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.sms_channel
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.user_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.sms_work
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsWork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.sms_send_code
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsSendCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.sms_send_status
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsSendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.sms_send_msg
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsSendMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.sms_check_code
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsCheckCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.sms_check_status
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsCheckStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.sms_check_msg
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String smsCheckMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.sms_send_time
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private Date smsSendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.sms_check_time
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private Date smsCheckTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.phone
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.status
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_send_check.remark
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_send_check
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.sms_id
     *
     * @return the value of sms_send_check.sms_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsId() {
        return smsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.sms_id
     *
     * @param smsId the value for sms_send_check.sms_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsId(String smsId) {
        this.smsId = smsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.req_id
     *
     * @return the value of sms_send_check.req_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getReqId() {
        return reqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.req_id
     *
     * @param reqId the value for sms_send_check.req_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setReqId(String reqId) {
        this.reqId = reqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.sms_channel
     *
     * @return the value of sms_send_check.sms_channel
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsChannel() {
        return smsChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.sms_channel
     *
     * @param smsChannel the value for sms_send_check.sms_channel
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsChannel(String smsChannel) {
        this.smsChannel = smsChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.user_id
     *
     * @return the value of sms_send_check.user_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.user_id
     *
     * @param userId the value for sms_send_check.user_id
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.sms_work
     *
     * @return the value of sms_send_check.sms_work
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsWork() {
        return smsWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.sms_work
     *
     * @param smsWork the value for sms_send_check.sms_work
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsWork(String smsWork) {
        this.smsWork = smsWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.sms_send_code
     *
     * @return the value of sms_send_check.sms_send_code
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsSendCode() {
        return smsSendCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.sms_send_code
     *
     * @param smsSendCode the value for sms_send_check.sms_send_code
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsSendCode(String smsSendCode) {
        this.smsSendCode = smsSendCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.sms_send_status
     *
     * @return the value of sms_send_check.sms_send_status
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsSendStatus() {
        return smsSendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.sms_send_status
     *
     * @param smsSendStatus the value for sms_send_check.sms_send_status
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsSendStatus(String smsSendStatus) {
        this.smsSendStatus = smsSendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.sms_send_msg
     *
     * @return the value of sms_send_check.sms_send_msg
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsSendMsg() {
        return smsSendMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.sms_send_msg
     *
     * @param smsSendMsg the value for sms_send_check.sms_send_msg
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsSendMsg(String smsSendMsg) {
        this.smsSendMsg = smsSendMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.sms_check_code
     *
     * @return the value of sms_send_check.sms_check_code
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsCheckCode() {
        return smsCheckCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.sms_check_code
     *
     * @param smsCheckCode the value for sms_send_check.sms_check_code
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsCheckCode(String smsCheckCode) {
        this.smsCheckCode = smsCheckCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.sms_check_status
     *
     * @return the value of sms_send_check.sms_check_status
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsCheckStatus() {
        return smsCheckStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.sms_check_status
     *
     * @param smsCheckStatus the value for sms_send_check.sms_check_status
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsCheckStatus(String smsCheckStatus) {
        this.smsCheckStatus = smsCheckStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.sms_check_msg
     *
     * @return the value of sms_send_check.sms_check_msg
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getSmsCheckMsg() {
        return smsCheckMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.sms_check_msg
     *
     * @param smsCheckMsg the value for sms_send_check.sms_check_msg
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsCheckMsg(String smsCheckMsg) {
        this.smsCheckMsg = smsCheckMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.sms_send_time
     *
     * @return the value of sms_send_check.sms_send_time
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public Date getSmsSendTime() {
        return smsSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.sms_send_time
     *
     * @param smsSendTime the value for sms_send_check.sms_send_time
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsSendTime(Date smsSendTime) {
        this.smsSendTime = smsSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.sms_check_time
     *
     * @return the value of sms_send_check.sms_check_time
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public Date getSmsCheckTime() {
        return smsCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.sms_check_time
     *
     * @param smsCheckTime the value for sms_send_check.sms_check_time
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setSmsCheckTime(Date smsCheckTime) {
        this.smsCheckTime = smsCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.phone
     *
     * @return the value of sms_send_check.phone
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.phone
     *
     * @param phone the value for sms_send_check.phone
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.status
     *
     * @return the value of sms_send_check.status
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.status
     *
     * @param status the value for sms_send_check.status
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_send_check.remark
     *
     * @return the value of sms_send_check.remark
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_send_check.remark
     *
     * @param remark the value for sms_send_check.remark
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_send_check
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", smsId=").append(smsId);
        sb.append(", reqId=").append(reqId);
        sb.append(", smsChannel=").append(smsChannel);
        sb.append(", userId=").append(userId);
        sb.append(", smsWork=").append(smsWork);
        sb.append(", smsSendCode=").append(smsSendCode);
        sb.append(", smsSendStatus=").append(smsSendStatus);
        sb.append(", smsSendMsg=").append(smsSendMsg);
        sb.append(", smsCheckCode=").append(smsCheckCode);
        sb.append(", smsCheckStatus=").append(smsCheckStatus);
        sb.append(", smsCheckMsg=").append(smsCheckMsg);
        sb.append(", smsSendTime=").append(smsSendTime);
        sb.append(", smsCheckTime=").append(smsCheckTime);
        sb.append(", phone=").append(phone);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}