package com.seesea.seeseasms.mapper;

import com.seesea.seeseasms.entity.SmsChannel;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface SmsChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    int deleteByPrimaryKey(String smsChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    int insert(SmsChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    SmsChannel selectByPrimaryKey(String smsChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    List<SmsChannel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_channel
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    int updateByPrimaryKey(SmsChannel record);

    @Select("select * from tb_sms_channel where remainder = (select min(remainder) from tb_sms_channel where status = '1')")
    List<SmsChannel> selectACanUseChannel();


    /**
     * 发一次减去一条
     *
     * @return
     */
    @Update("UPDATE tb_sms_channel set remainder = remainder-1")
    int updateChannlRemainder();
}