package com.seesea.seeseasms.mapper;

import com.seesea.seeseasms.entity.SmsSendCheck;
import java.util.List;

public interface SmsSendCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_send_check
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    int deleteByPrimaryKey(String smsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_send_check
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    int insert(SmsSendCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_send_check
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    SmsSendCheck selectByPrimaryKey(String smsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_send_check
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    List<SmsSendCheck> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_send_check
     *
     * @mbg.generated Tue Nov 24 20:16:45 CST 2020
     */
    int updateByPrimaryKey(SmsSendCheck record);
}