package com.seesea.seeseagateway.entity;

import java.io.Serializable;
import java.util.Date;

public class AccountInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account_id
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account_key
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    private String accountKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account_secret
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    private String accountSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account_name
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.id_card
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.id_type
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    private String idType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.level
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.create_time
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.update_time
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.status
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account_id
     *
     * @return the value of account_info.account_id
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account_id
     *
     * @param accountId the value for account_info.account_id
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account_key
     *
     * @return the value of account_info.account_key
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public String getAccountKey() {
        return accountKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account_key
     *
     * @param accountKey the value for account_info.account_key
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public void setAccountKey(String accountKey) {
        this.accountKey = accountKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account_secret
     *
     * @return the value of account_info.account_secret
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public String getAccountSecret() {
        return accountSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account_secret
     *
     * @param accountSecret the value for account_info.account_secret
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public void setAccountSecret(String accountSecret) {
        this.accountSecret = accountSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account_name
     *
     * @return the value of account_info.account_name
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account_name
     *
     * @param accountName the value for account_info.account_name
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.id_card
     *
     * @return the value of account_info.id_card
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.id_card
     *
     * @param idCard the value for account_info.id_card
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.id_type
     *
     * @return the value of account_info.id_type
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.id_type
     *
     * @param idType the value for account_info.id_type
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public void setIdType(String idType) {
        this.idType = idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.level
     *
     * @return the value of account_info.level
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.level
     *
     * @param level the value for account_info.level
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.create_time
     *
     * @return the value of account_info.create_time
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.create_time
     *
     * @param createTime the value for account_info.create_time
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.update_time
     *
     * @return the value of account_info.update_time
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.update_time
     *
     * @param updateTime the value for account_info.update_time
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.status
     *
     * @return the value of account_info.status
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.status
     *
     * @param status the value for account_info.status
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Mon Nov 23 19:58:12 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", accountId=").append(accountId);
        sb.append(", accountKey=").append(accountKey);
        sb.append(", accountSecret=").append(accountSecret);
        sb.append(", accountName=").append(accountName);
        sb.append(", idCard=").append(idCard);
        sb.append(", idType=").append(idType);
        sb.append(", level=").append(level);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}