package com.seesea.seeseagateway.entity;

import java.io.Serializable;

public class ServiceInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_info.service_id
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    private String serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_info.application_id
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    private String applicationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_info.service_name
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    private String serviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_info.service_remark
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    private String serviceRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_info.service_url
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    private String serviceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_info.is_check
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    private Boolean isCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table service_info
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_info.service_id
     *
     * @return the value of service_info.service_id
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_info.service_id
     *
     * @param serviceId the value for service_info.service_id
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_info.application_id
     *
     * @return the value of service_info.application_id
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_info.application_id
     *
     * @param applicationId the value for service_info.application_id
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_info.service_name
     *
     * @return the value of service_info.service_name
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_info.service_name
     *
     * @param serviceName the value for service_info.service_name
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_info.service_remark
     *
     * @return the value of service_info.service_remark
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    public String getServiceRemark() {
        return serviceRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_info.service_remark
     *
     * @param serviceRemark the value for service_info.service_remark
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    public void setServiceRemark(String serviceRemark) {
        this.serviceRemark = serviceRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_info.service_url
     *
     * @return the value of service_info.service_url
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    public String getServiceUrl() {
        return serviceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_info.service_url
     *
     * @param serviceUrl the value for service_info.service_url
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    public void setServiceUrl(String serviceUrl) {
        this.serviceUrl = serviceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_info.is_check
     *
     * @return the value of service_info.is_check
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    public Boolean getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_info.is_check
     *
     * @param isCheck the value for service_info.is_check
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    public void setIsCheck(Boolean isCheck) {
        this.isCheck = isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated Thu Nov 19 20:14:31 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", serviceId=").append(serviceId);
        sb.append(", applicationId=").append(applicationId);
        sb.append(", serviceName=").append(serviceName);
        sb.append(", serviceRemark=").append(serviceRemark);
        sb.append(", serviceUrl=").append(serviceUrl);
        sb.append(", isCheck=").append(isCheck);
        sb.append("]");
        return sb.toString();
    }
}